services:
  web:
    build: .
    container_name: intranet_web
    ports:
      - "5000:5000"
    environment:
    # secret key set avec la commande openssl rand -base64 32
      - DATABASE_URL=mysql+pymysql://intranet_user:zpS9AKfVqPiTKTy6ccUdmZe1uijPx7wc@db:3306/intranet
      - FLASK_SECRET_KEY=foktoNGvhRY8tjPvrtKw3D46gNeVhGQq9ChDl8vv2J8=
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

############################################
#           mise en place de la db         #
############################################
  db:
    image: mysql:8
    container_name: intranet_db
    restart: unless-stopped
    environment:
    # mdp set avec la commande openssl rand -base64 24
      MYSQL_ROOT_PASSWORD: hBTrghSeoBViPL1YPZRJCS99gE3g7zF2
      MYSQL_DATABASE: intranet
      MYSQL_USER: intranet_user
      MYSQL_PASSWORD: zpS9AKfVqPiTKTy6ccUdmZe1uijPx7wc
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    # checker la connexion avec la db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-phBTrghSeoBViPL1YPZRJCS99gE3g7zF2"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

